name: Awakened Heart Sangha
favicon: null
layout_spectrum: 0.2270479816943407
typography_spectrum: 0.32909774081781507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.30114920740015805
  lightness: 0.6396506384480745
  saturation: 0.7646182617172599
  rhythmicContrast: 0.2460381535347551
purpose: []
