name: Awakened Heart Sangha
favicon: null
layout_spectrum: 0.90082
typography_spectrum: 0.72987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0e100d'
    - '#177e4f'
    - '#921328'
    - '#8aaf2c'
  brandStrength: 0.30114920740015805
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
